/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React from 'react'
import { Clone, useGLTF, 

 } from '@react-three/drei'


export default function Plant2(props) {
  const model = useGLTF('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/cactus/model.gltf')
  return (
    <Clone {...props} object={model.scene} /> 
    
  )
}

useGLTF.preload('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/cactus/model.gltf')