/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import {
    Clone,
    useGLTF,

} from '@react-three/drei'


export default function Table(props) {
    const model = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/bench-2/model.gltf')
    return (
        <mesh castShadow>
            <Clone {...props} object={model.scene} /> 

        </mesh>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/bench-2/model.gltf')